In [3]:
# Vamos a escribir un codigo para ir calculando el gradient descent sobre una red simple de 3 neuronas de entrada
# y una de salida.


import numpy as np


# los pesos son:
weights = np.array([0, 2, 1])

# y los valores de de entrada son 
input_data = np.array([1, 2, 3])

# valor real de la salida
target = 0


In [7]:
# primero calculemos las predicciones:
preds = sum(weights * input_data)
preds

7

In [8]:
# ahora calculamos el error
error = preds - target
error

7

In [10]:
# y finalmente la pendiente de la funcion de perdida con respecto a la prediccion.:

slope = 2 * input_data * error
slope


# nota:  ¿por qué va el 2?
# R: como funcion de perdida estamso utilizando el MSE, es decir (prediccion - real)^2. 
# La derivada de esto, siempre va multiplicada por 2.

array([14, 28, 42])

In [11]:
############

In [12]:
# ahora haremos una actualizacion de los pesos.
# con LR 

learning_rate = 0.01

In [23]:
# hagamos el upgrade de pesos 
weights_updated = weights - learning_rate * slope

print(weights)
print(weights_updated)

[0 2 1]
[-0.14  1.72  0.58]


In [24]:
# prediccion con los nuevos pesos
preds_updated = (weights_updated * input_data).sum()

preds_updated

5.04

In [25]:
# el nuevo error seria:

error_updated = preds_updated - target

print(error)
print(error_updated)

7
5.04


In [ ]:
############
############
############